function [fitresult, gof] = createXinFit(T1f, X1f, T2f)
%CREATEFIT(T1F,X1F,T2F)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : T1f
%      Y Input : X1f
%      Z Output: T2f
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Sep-2015 10:21:17


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( T1f, X1f, T2f );

% Set up fittype and options.
ft = 'thinplateinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'T2f vs. T1f, X1f', 'Location', 'NorthEast' );
% Label axes
xlabel T1f
ylabel X1f
zlabel T2f
grid on
view( -83.5, 22.0 );


